# serverless.yml

service: lambda-schedule-ecs

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: development-bincard-apii

functions:
  app:
    handler: app.handler # reference the file and exported method
    events: # events trigger lambda functions
      - schedule:
          rate: cron(0 23 * * ? *)
          input:
            action: stop
            region: us-east-1
            clusterName: financob
            serviceToStop: api_dev
      - schedule:
          rate: cron(0 7 * * ? *)
          input:
            action: start
            region: us-east-1
            clusterName: financob
            desiredCount: 1
            serviceToStart: api_dev
